### ISSUE TITLE
It isn't working anymore

### ISSUE THREAD

**Issue by geraldosales** [SDWebImage/SDWebImageBPGCoder#9]
Hi. I am trying to create a bpg image from a data array, using SDImageCodersManager.shared.decodedImage(with: newgData) but all the time I only receive a message on log sayng "CGImageCreate: invalid image byte order info for bitsPerPixel != 32 = 16384"

when I check with SDImageCodersManager.shared.canDecode(from: newgData) I get a true, but o decode doesn't work.

This is occuring on xCode 14.3, macOS 13.4 running on iOS 16.4.

I have no idea how to solve this.

Can you help me with this issue?

Regards

**Comment by dreampiggy** [comment]
I know how to fix this, this is the same issue in SDWebImage Core from iOS 15

But actually, BPG is no longer maintained so this repo should be treated as archive...(BPG lose in the Image Format competition to WebP/HEIF and will disappear soon)


https://github.com/SDWebImage/SDWebImage/pull/3332

**Comment by dreampiggy** [comment]
Will fix and release a maintainess version. But there are no more feature added (Like SDWebImage 5.16.0 Core new feature called `limitBytes during decoding`)

**Comment by dreampiggy** [comment]
Fixed in 0.7.2

**Comment by geraldosales** [comment]
Hi! 
I would like to thank you.
It's all right !
